### ISSUE TITLE
Release 0.4.0 on npm

### ISSUE THREAD

**Issue by letmaik** [aaronhuggins/cbor-redux#10]
For some reason 0.4.0 is not on npm. It misses important fixes like tagged value encoding.

**Comment by aaronhuggins** [comment]
Thanks for bringing this up. I've been ill the last few days. I'll get a release cut once I'm well, probably in the next few days.

**Comment by letmaik** [comment]
Ping

**Comment by aaronhuggins** [comment]
@letmaik Pong. Trying to queue up time to do maintenance on this. Really struggling w/ home life.

**Comment by letmaik** [comment]
No worries, let me know if I can help somehow. What I typically do is automate publishing in CI. Here's a useful guide where the trigger is the creation of a GitHub release: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

**Comment by aaronhuggins** [comment]
I think I'm coming up on a window where I can work this. I'll get 0.4.0 on npm this week pre-migration. Post-migration to single unified codebase, I'll publish another version with all remaining updates.

**Comment by aaronhuggins** [comment]
Ha. Found time today. https://www.npmjs.com/package/cbor-redux/v/0.4.0

![BOOM!](https://media1.giphy.com/media/laUY2MuoktHPy/200.gif)
