### ISSUE TITLE
Add CBOR Support for Typed Arrays

### ISSUE THREAD

**Issue by glenne** [aaronhuggins/cbor-redux#13]
[RFC8746 CBOR tags for Typed Arrays](https://datatracker.ietf.org/doc/html/rfc8746) defines tags for encoding typed arrays such as Float32Array and Int16Array.  By using the tags, applications can round-trip these arrays without using blobs so they retain the self-defining nature of CBOR.  See Pull request #14 for implementation.

**Comment by aaronhuggins** [comment]
Sorry for the extremely long delay. Great work, thank you so much for the contribution. I am making plans to get this in this month.

**Comment by aaronhuggins** [comment]
@glenne How do you want attribution for your code contributions? I'd like to credit you in the NPM package and the README.

Here's how I've currently got it set for the NPM package: https://github.com/aaronhuggins/cbor-redux/blob/a5fb707d21a3e0c2da10acde20c8eafd095de2de/scripts/build_npm.ts#L64

I've grabbed that bit from your git commits in the log.

**Comment by glenne** [comment]
That looks fine to me.  Thanks for merging the pull request too.  I'm quite
OK with tweaking the api to your preferences.

Glenn
