### ISSUE TITLE
Question: Why this module has "-redux" suffix?

### ISSUE THREAD

**Issue by lambdalisue** [aaronhuggins/cbor-redux#9]
I'd like to use CBOR in deno and I found this module. 

It seems good but I wonder why the name has "-redux" suffix. 
Is this module related to Redux or planning to relies on the Redux?

I'm afraid that while I don't want to rely on Redux for encoding/decoding CBOR...

**Comment by aaronhuggins** [comment]
It's perhaps silly, but it means "brought back". https://www.merriam-webster.com/dictionary/redux

Never occurred to me it would be confused with another software.

There's no dependency or relationship to the software named Redux.

**Comment by PathToLife** [comment]
i thought this was related to redux as well - thanks for the clarification - it might be good to add this to the readme :)
